--------------------------------------------------------
--  Arquivo criado - sexta-feira-maio-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIM_CIDADE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DIM_CIDADE" 
   (	"CIDADE_ID" NUMBER, 
	"CIDADE_NOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ESTADO_ID" NUMBER, 
	"UF" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"FUSO_HORARIO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table DIM_ESTADO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DIM_ESTADO" 
   (	"ESTADO_ID" NUMBER, 
	"UF" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"ESTADO_NOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table FATO_CLIMA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."FATO_CLIMA" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CIDADE_ID" NUMBER, 
	"DATA_COLETA" DATE, 
	"TEMPERATURA_MIN" NUMBER, 
	"TEMPERATURA_MAX" NUMBER, 
	"SENSACAO_TERMICA" NUMBER, 
	"UMIDADE" NUMBER, 
	"VENTO_VELOCIDADE" NUMBER, 
	"CHUVA_PROBABILIDADE" NUMBER, 
	"DESCRICAO_CLIMA" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_CIDADE_GEO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."STG_CIDADE_GEO" 
   (	"CIDADE_ID" NUMBER, 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"FUSO_HORARIO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"NOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
REM INSERTING into ADMIN.DIM_CIDADE
SET DEFINE OFF;
